### ISSUE TITLE
OptiPlex 7050 firmware needs to be updated

### ISSUE THREAD

**Issue by meeldrid** [hughsie/fwupd#427] opened 2018-03-02 19:10 UTC
The current version of the OptiPlex 7050 firmware in [fwupd is 1.5.2](https://fwupd.org/lvfs/device/4fed6c9d-22b0-4731-a074-084ba68b492a). [Version 1.7.9](http://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=MGJW2) is available on Dell's support site.

**Comment by superm1** [comment] 2018-03-06 07:04
In the future file issues on missing firmware to https://github.com/hughsie/lvfs-website.  This is a duplicate of https://github.com/hughsie/lvfs-website/issues/34 which was recently resolved.

**Closed by superm1** 2018-03-06 07:04 UTC
