### ISSUE TITLE
Got this error "Could not apply capsule update: Not Found"

### ISSUE THREAD

**Issue by sudoyang** [hughsie/fwupd#989] opened 2019-02-01 18:01 UTC
Found update fwupd-798ffd60-f10e-4ac4-8939-c8beabfe55b4-0
File \EFI\ubuntu\fw\fwupd-798ffd60-f10e-4ac4-8939-c8beabfe55b4-0 searched
Could not apply capsule update: Not Found
fwupdate: Could not apply capsules: Not Found
start_image() returned Not Found

My machine is X1 carbon 5gen

```shell
$ fwupdmgr --version

client version:	1.1.2
daemon version:	1.1.2
compile-time dependency versions
	appstream-glib:	0.7.12
	gusb:	0.2.11
	efivar:	34

```

Note, the switch `--version` is only present since version 0.9.6. If you use an
earlier version, please use the package manager to find out the package
version. For example, `dpkg -l fwupd`.

```shell
$ fwupdmgr get-devices

20HRCTO1WW System Firmware
  DeviceId:             1cbe298fc17877b6883e85560778ac0812f0a385
  Guid:                 798ffd60-f10e-4ac4-8939-c8beabfe55b4
  Guid:                 8f58d6d2-9753-5def-8169-1ef0971b1edc
  Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              0.1.35
  VersionLowest:        0.1.14
  Icon:                 computer
  Created:              2019-02-01
  UpdateState:          success

UEFI Device Firmware
  DeviceId:             4af4b60cae789891a862f14e995f9b0bcb75c2e2
  Guid:                 1c7df930-c51b-43f2-af4e-01239686ff2d
  Guid:                 4b1468ba-bb93-51e0-952b-76b21589040b
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              184.55.3510
  VersionLowest:        0.0.1
  Icon:                 audio-card
  Created:              2019-02-01

UEFI Device Firmware
  DeviceId:             6b3fcb33b92ea5cdd94954b276ad0b63ed14f9bb
  Guid:                 74997a6b-1adf-4b12-b994-401f06ea8c72
  Guid:                 1fe412bc-cb71-5d49-8812-8198a006fa58
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|registered|needs-reboot
  Version:              0.1.19
  VersionLowest:        0.0.1
  Icon:                 audio-card
  Created:              2019-02-01

ThinkPad X1 Carbon Thunderbolt Controller
  DeviceId:             8dad23fff29e05c18d0fd24ee216a115e052b146
  Guid:                 89d9d1e6-9e4c-5f07-b5c1-603da3d61835
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|registered
  Vendor:               Lenovo
  VendorId:             TBT:0x0109
  Version:              15.00
  Icon:                 computer
  Created:              2019-02-01

________________________________________________

Devices that have been updated successfully:

 • 20HRCTO1WW System Firmware (0.1.34 → 0.1.35)

Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Upload report now? (Requires internet connection) [Y|n]: n


```

```shell
$ efibootmgr -v

BootCurrent: 0001
Timeout: 0 seconds
BootOrder: 0001,0000,0017,0018,0019,001A,001B,001C,001D,001E
Boot0000* Windows Boot Manager	HD(1,GPT,526fe205-888f-4d42-b548-087a87010b49,0x800,0x82000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}...e................
Boot0001* ubuntu	HD(1,GPT,0288891b-3a87-4aa9-b5b3-93f9876c54d8,0x800,0x11d800)/File(\EFI\ubuntu\shimx64.efi)
Boot0010  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu	FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen	FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics	FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  Startup Interrupt Menu	FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0015  Rescue and Recovery	FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0016  MEBx Hot Key	FvFile(ac6fd56a-3d41-4efd-a1b9-870293811a28)
Boot0017* USB CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot0018* USB FDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot0019* NVMe0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001A* ATA HDD0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001B* USB HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot001C* PCI LAN	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot001D  Other CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a35406)
Boot001E  Other HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f606)
Boot001F* IDER BOOT CDROM	PciRoot(0x0)/Pci(0x16,0x2)/Ata(0,1,0)
Boot0020* IDER BOOT Floppy	PciRoot(0x0)/Pci(0x16,0x2)/Ata(0,0,0)
Boot0021* ATA HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f6)
Boot0022* ATAPI CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a354)

**This is only required if you use the UEFI plugin**
```

```shell
$ efivar -l | grep fw

zsh: command not found: efivar
It seems that I do not have this.
**This is only required if you use the UEFI plugin**
```

```shell
$ tree /boot

/boot
├── abi-4.13.0-36-generic
├── abi-4.18.0-12-generic
├── config-4.13.0-36-generic
├── config-4.18.0-12-generic
├── config-4.18.0-13-generic
├── efi
│   └── EFI
│       ├── BOOT
│       │   ├── BOOTX64.EFI
│       │   ├── fbx64.efi
│       │   └── mmx64.efi
│       └── ubuntu
│           ├── BOOTX64.CSV
│           ├── fw
│           ├── fwupdx64.efi
│           ├── grub.cfg
│           ├── grubx64.efi
│           ├── mmx64.efi
│           └── shimx64.efi
├── grub
│   ├── fonts
│   │   ├── DejaVuSansMono24.pf2
│   │   └── unicode.pf2
│   ├── grub.cfg
│   ├── grubenv
│   ├── locale
│   │   ├── en_AU.mo
│   │   ├── en_CA.mo
│   │   ├── en_GB.mo
│   │   ├── en@quot.mo
│   │   ├── zh_CN.mo
│   │   ├── zh_HK.mo
│   │   └── zh_TW.mo
│   ├── themes
│   ├── unicode.pf2
│   └── x86_64-efi
│       ├── acpi.mod
│       ├── adler32.mod
│       ├── affs.mod
│       ├── afs.mod
│       ├── ahci.mod
│       ├── all_video.mod
│       ├── aout.mod
│       ├── appleldr.mod
│       ├── archelp.mod
│       ├── ata.mod
│       ├── at_keyboard.mod
│       ├── backtrace.mod
│       ├── bfs.mod
│       ├── bitmap.mod
│       ├── bitmap_scale.mod
│       ├── blocklist.mod
│       ├── boot.mod
│       ├── bsd.mod
│       ├── bswap_test.mod
│       ├── btrfs.mod
│       ├── bufio.mod
│       ├── cat.mod
│       ├── cbfs.mod
│       ├── cbls.mod
│       ├── cbmemc.mod
│       ├── cbtable.mod
│       ├── cbtime.mod
│       ├── chain.mod
│       ├── cmdline_cat_test.mod
│       ├── cmp.mod
│       ├── cmp_test.mod
│       ├── command.lst
│       ├── configfile.mod
│       ├── core.efi
│       ├── cpio_be.mod
│       ├── cpio.mod
│       ├── cpuid.mod
│       ├── crc64.mod
│       ├── cryptodisk.mod
│       ├── crypto.lst
│       ├── crypto.mod
│       ├── cs5536.mod
│       ├── ctz_test.mod
│       ├── datehook.mod
│       ├── date.mod
│       ├── datetime.mod
│       ├── diskfilter.mod
│       ├── disk.mod
│       ├── div.mod
│       ├── div_test.mod
│       ├── dm_nv.mod
│       ├── echo.mod
│       ├── efifwsetup.mod
│       ├── efi_gop.mod
│       ├── efinet.mod
│       ├── efi_uga.mod
│       ├── ehci.mod
│       ├── elf.mod
│       ├── eval.mod
│       ├── exfat.mod
│       ├── exfctest.mod
│       ├── ext2.mod
│       ├── extcmd.mod
│       ├── fat.mod
│       ├── file.mod
│       ├── fixvideo.mod
│       ├── font.mod
│       ├── fshelp.mod
│       ├── fs.lst
│       ├── functional_test.mod
│       ├── gcry_arcfour.mod
│       ├── gcry_blowfish.mod
│       ├── gcry_camellia.mod
│       ├── gcry_cast5.mod
│       ├── gcry_crc.mod
│       ├── gcry_des.mod
│       ├── gcry_dsa.mod
│       ├── gcry_idea.mod
│       ├── gcry_md4.mod
│       ├── gcry_md5.mod
│       ├── gcry_rfc2268.mod
│       ├── gcry_rijndael.mod
│       ├── gcry_rmd160.mod
│       ├── gcry_rsa.mod
│       ├── gcry_seed.mod
│       ├── gcry_serpent.mod
│       ├── gcry_sha1.mod
│       ├── gcry_sha256.mod
│       ├── gcry_sha512.mod
│       ├── gcry_tiger.mod
│       ├── gcry_twofish.mod
│       ├── gcry_whirlpool.mod
│       ├── geli.mod
│       ├── gettext.mod
│       ├── gfxmenu.mod
│       ├── gfxterm_background.mod
│       ├── gfxterm_menu.mod
│       ├── gfxterm.mod
│       ├── gptsync.mod
│       ├── grub.efi
│       ├── gzio.mod
│       ├── halt.mod
│       ├── hashsum.mod
│       ├── hdparm.mod
│       ├── hello.mod
│       ├── help.mod
│       ├── hexdump.mod
│       ├── hfs.mod
│       ├── hfspluscomp.mod
│       ├── hfsplus.mod
│       ├── http.mod
│       ├── iorw.mod
│       ├── iso9660.mod
│       ├── jfs.mod
│       ├── jpeg.mod
│       ├── keylayouts.mod
│       ├── keystatus.mod
│       ├── ldm.mod
│       ├── legacycfg.mod
│       ├── legacy_password_test.mod
│       ├── linux16.mod
│       ├── linuxefi.mod
│       ├── linux.mod
│       ├── loadbios.mod
│       ├── load.cfg
│       ├── loadenv.mod
│       ├── loopback.mod
│       ├── lsacpi.mod
│       ├── lsefimmap.mod
│       ├── lsefi.mod
│       ├── lsefisystab.mod
│       ├── lsmmap.mod
│       ├── ls.mod
│       ├── lspci.mod
│       ├── lssal.mod
│       ├── luks.mod
│       ├── lvm.mod
│       ├── lzopio.mod
│       ├── macbless.mod
│       ├── macho.mod
│       ├── mdraid09_be.mod
│       ├── mdraid09.mod
│       ├── mdraid1x.mod
│       ├── memdisk.mod
│       ├── memrw.mod
│       ├── minicmd.mod
│       ├── minix2_be.mod
│       ├── minix2.mod
│       ├── minix3_be.mod
│       ├── minix3.mod
│       ├── minix_be.mod
│       ├── minix.mod
│       ├── mmap.mod
│       ├── moddep.lst
│       ├── modinfo.sh
│       ├── morse.mod
│       ├── mpi.mod
│       ├── msdospart.mod
│       ├── mul_test.mod
│       ├── multiboot2.mod
│       ├── multiboot.mod
│       ├── nativedisk.mod
│       ├── net.mod
│       ├── newc.mod
│       ├── nilfs2.mod
│       ├── normal.mod
│       ├── ntfscomp.mod
│       ├── ntfs.mod
│       ├── odc.mod
│       ├── offsetio.mod
│       ├── ohci.mod
│       ├── part_acorn.mod
│       ├── part_amiga.mod
│       ├── part_apple.mod
│       ├── part_bsd.mod
│       ├── part_dfly.mod
│       ├── part_dvh.mod
│       ├── part_gpt.mod
│       ├── partmap.lst
│       ├── part_msdos.mod
│       ├── part_plan.mod
│       ├── part_sun.mod
│       ├── part_sunpc.mod
│       ├── parttool.lst
│       ├── parttool.mod
│       ├── password.mod
│       ├── password_pbkdf2.mod
│       ├── pata.mod
│       ├── pbkdf2.mod
│       ├── pbkdf2_test.mod
│       ├── pcidump.mod
│       ├── play.mod
│       ├── png.mod
│       ├── priority_queue.mod
│       ├── probe.mod
│       ├── procfs.mod
│       ├── progress.mod
│       ├── raid5rec.mod
│       ├── raid6rec.mod
│       ├── random.mod
│       ├── read.mod
│       ├── reboot.mod
│       ├── regexp.mod
│       ├── reiserfs.mod
│       ├── relocator.mod
│       ├── romfs.mod
│       ├── scsi.mod
│       ├── search_fs_file.mod
│       ├── search_fs_uuid.mod
│       ├── search_label.mod
│       ├── search.mod
│       ├── serial.mod
│       ├── setjmp.mod
│       ├── setjmp_test.mod
│       ├── setpci.mod
│       ├── sfs.mod
│       ├── shift_test.mod
│       ├── signature_test.mod
│       ├── sleep.mod
│       ├── sleep_test.mod
│       ├── spkmodem.mod
│       ├── squash4.mod
│       ├── syslinuxcfg.mod
│       ├── tar.mod
│       ├── terminal.lst
│       ├── terminal.mod
│       ├── terminfo.mod
│       ├── test_blockarg.mod
│       ├── testload.mod
│       ├── test.mod
│       ├── testspeed.mod
│       ├── tftp.mod
│       ├── tga.mod
│       ├── time.mod
│       ├── trig.mod
│       ├── tr.mod
│       ├── true.mod
│       ├── udf.mod
│       ├── ufs1_be.mod
│       ├── ufs1.mod
│       ├── ufs2.mod
│       ├── uhci.mod
│       ├── usb_keyboard.mod
│       ├── usb.mod
│       ├── usbms.mod
│       ├── usbserial_common.mod
│       ├── usbserial_ftdi.mod
│       ├── usbserial_pl2303.mod
│       ├── usbserial_usbdebug.mod
│       ├── usbtest.mod
│       ├── verify.mod
│       ├── video_bochs.mod
│       ├── video_cirrus.mod
│       ├── video_colors.mod
│       ├── video_fb.mod
│       ├── videoinfo.mod
│       ├── video.lst
│       ├── video.mod
│       ├── videotest_checksum.mod
│       ├── videotest.mod
│       ├── xfs.mod
│       ├── xnu.mod
│       ├── xnu_uuid.mod
│       ├── xnu_uuid_test.mod
│       ├── xzio.mod
│       ├── zfscrypt.mod
│       ├── zfsinfo.mod
│       └── zfs.mod
├── initrd.img-4.13.0-36-generic
├── initrd.img-4.18.0-12-generic
├── initrd.img-4.18.0-13-generic
├── memtest86+.bin
├── memtest86+.elf
├── memtest86+_multiboot.bin
├── retpoline-4.13.0-36-generic
├── retpoline-4.18.0-12-generic
├── System.map-4.13.0-36-generic
├── System.map-4.18.0-12-generic
├── System.map-4.18.0-13-generic
├── vmlinuz-4.13.0-36-generic
├── vmlinuz-4.13.0-41-generic.efi.signed
├── vmlinuz-4.18.0-12-generic
└── vmlinuz-4.18.0-13-generic

10 directories, 309 files


**This is only required if you use the UEFI plugin**
**We're looking for any `.cap` files and the location of `fwupx64.efi`**
```

Please answer the following questions:

- Operating system and version:
Ubuntu 18.10
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc):
apt-get
- Have you tried rebooting?
yes
- Are you using an NVMe disk?
No
- Is secure boot enabled (only for the UEFI plugin)?
I tried both. But either enable or not give me same error messages. 

I was able to use it update bios successfully. I remember one time I delete my EFI partition by mistake and ask my friend help me to use some command to restore the EFI partition. Maybe the restore causes the issue here?

Below it should be a set of commands used to restore EFI partition. It might be wrong since I do not remember it clearly.

 9607  sudo grub-install /dev/sda1
 9608  cat /etc/fastb
 9609  cat /etc/fstab
 9610  ls -l /
 9611  ls -l /boot
 9612  ls -l /boot/efi
 9613  sudo vi /etc/fstab
 9614  sudo mount /boot/efi
 9615  monut
 9616  mount
 9617  sudo grub-mkconfig
 9618  sudo grub-mkconfig --help
 9619  sudo grub-install --help
 9620  sudo grub-install /dev/sda
 9621  ls -l efi
 9622  ls -l efi/EFI

**Comment by superm1** [comment] 2019-02-04 14:55
Can you guys retry using the [fwupd snap](https://github.com/hughsie/fwupd/wiki/fwupd-snap)?

**Comment by sudoyang** [comment] 2019-02-05 23:59
@superm1  I tried but it failed. Please see the picture.

![photo feb 05 6 56 33 pm](https://user-images.githubusercontent.com/2531404/52312281-0a789600-2978-11e9-882e-6d8eb5317fee.png)

@ilya40umov  You can see there is a EFI label.

![captured_20190205_18 53 27_001](https://user-images.githubusercontent.com/2531404/52312311-2a0fbe80-2978-11e9-98ee-1b94e8a343c0.png)

**Comment by superm1** [comment] 2019-02-25 18:39
decided Duplicate of #1037

**Closed by superm1** 2019-02-25 18:39 UTC
Labels: duplicate, vendor-bug

**Comment by n-peugnet** [comment] 2019-12-10 23:19
> What helped in my case was a full re-install where I let the installer create all necessary partitions for UEFI boot.
> I suspect this issue might have something to do with some properties of `/boot/efi` partition which the installer (unlike me) would set properly.
> Can you run GParted and check if EFI partition has the following flags: `boot, esp`?

Hi @ilya40umov, I am almost in the exact same case (except that I added that partition afterwards as I first installed linux for a legacy BIOS)  and I would like not to reinstall the system. Could you please give me more infos on the specificity of your working partition ?

Here is mine, I added the `esp` flag because of you comment but it is still not working:
![uefi-partition](https://user-images.githubusercontent.com/23519418/70577252-27d74b80-1bab-11ea-8c37-7b56f59d5e5d.png)

By the way, I don't really think that it's the same issue as the one pointed as duplicate.

**Comment by megatog615** [comment] 2023-07-12 03:54
For anyone arrive here from Google(or what have you), I have solved this problem by ensuring the ESP partition is labelled "ESP"(no quotes) and the esp and boot flags are enabled. You can enable the esp flag in parted, which automatically added the boot flag as well. Previously, my ESP partition was labelled "ESD" and had only the msftdata flag enabled. Keep in mind enabling the esp flag will disable msftdata for some reason.

In any case, I was able to install the firmware by doing this.

**Comment by sliedes** [comment] 2025-01-01 13:28
I saw this happen (on a ThinkPad E14 Gen 6) when I had a USB stick with an ESP partition (that I had used to do other firmware updates) inserted. My best guess is that fwupdx64.efi or whatever tried to load the capsules from that instead of the EFI partition that I booted from. Unplugging the USB stick allowed the update to succeed.
