### ISSUE TITLE
Unable to switch TPM mode on XPS 9550

### ISSUE THREAD

**Issue by gentoochainsaw** [hughsie/fwupd#775] opened 2018-10-01 14:16 UTC
To help us pinpoint your issue, please insert the output of the
following commands when ran on the system with the issue:

```
$ fwupdmgr --version
client version:	1.1.2
daemon version:	1.1.2
compile-time dependency versions
	appstream-glib:	0.7.9
	gusb:	0.2.11
	efivar:	36

XPS 15 9550 TPM 1.2
  DeviceId:             5ab1e5b4c5e2639722437a5b7c5a8391c75fcabe
  Guid:                 9055a777-a92f-55da-8d34-6614d8f9df92
  Guid:                 a4f7987a-5837-5ac6-b579-60ce4e358f84
  Summary:              Platform TPM device
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Vendor:               Dell Inc.
  Version:              5.81.2.1
  Icon:                 computer
  Created:              2018-10-01

XPS15 9550 Thunderbolt Controller
  DeviceId:             84e567453922d3ba97ca4c7261bbf62508ec1727
  Guid:                 c2ca983d-a03d-56c6-80c4-fbb38d829f50
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|supported|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              26.01
  Icon:                 computer
  Created:              2018-10-01

Dell Thunderbolt Cable
  DeviceId:             2e3d37ac318c476635bff9dc8ba53e151d42eabf
  ParentDeviceId:       84edf044a6b53037732cfc7591b65a8d36384cc9
  Guid:                 b4fd3cdf-4e3a-5090-a583-45367cfd6421
  Plugin:               thunderbolt
  Flags:                updatable|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              16.00
  Icon:                 audio-card
  Created:              2018-10-01

Dell Thunderbolt Dock
  DeviceId:             72fd241e50970edb9a150188bb9af8cc8cc535e8
  ParentDeviceId:       84edf044a6b53037732cfc7591b65a8d36384cc9
  Guid:                 76cc74d4-f062-5b93-a11c-8d2a58a25848
  Plugin:               thunderbolt
  Flags:                updatable|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              16.00
  Icon:                 audio-card
  Created:              2018-10-01

Synaptics VMM3320 inside Dell WD15/TB16/TB18 wired Dock
  DeviceId:             7b3cbc344094ace839263dd4711c84ea99bb6dc3
  ParentDeviceId:       84edf044a6b53037732cfc7591b65a8d36384cc9
  Guid:                 152a9833-41e6-5c21-9dde-0ff8984f3e20
  Guid:                 0a52c8c7-26d5-59a0-ae44-6b00e276d775
  Guid:                 51000744-2de6-5a52-8a86-d5f69fd73d34
  Summary:              Multi-Stream Transport Device
  Plugin:               synapticsmst
  Flags:                updatable|registered
  Vendor:               Synaptics
  Version:              3.10.002
  Icon:                 computer
  Created:              2018-10-01

Synaptics VMM3330 inside Dell WD15/TB16/TB18 wired Dock
  DeviceId:             d83854e8c81f5d47b0b99c8a3b42ae5127c75eb8
  ParentDeviceId:       84edf044a6b53037732cfc7591b65a8d36384cc9
  Guid:                 c0f73159-4fc0-509b-80f8-5f871f3751a8
  Guid:                 be025b25-ca5c-546c-97c6-ee2160ba489d
  Guid:                 190e8d7c-6bcf-5fab-94e7-4f8739eb90aa
  Summary:              Multi-Stream Transport Device
  Plugin:               synapticsmst
  Flags:                updatable|registered
  Vendor:               Synaptics
  Version:              3.10.002
  Icon:                 computer
  Created:              2018-10-01

XPS 15 9550 System Firmware
  DeviceId:             2da31270d317b076424992de14a0f08ae373c137
  Guid:                 124c207d-5db8-4d95-bd31-34fd971b34f9
  Guid:                 0d25ab20-f5f1-591f-8baf-c59f009f9548
  Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              0.1.8.0
  VersionLowest:        0.1.8.0
  Icon:                 computer
  Created:              2018-10-01

Dell TB16 Thunderbolt Cable
  DeviceId:             f8194a42320518472a2e67c1d89018c7a5219841
  ParentDeviceId:       84edf044a6b53037732cfc7591b65a8d36384cc9
  Guid:                 6dc832fc-5bb0-4e63-a2ff-02aaba5bc1dc
  Guid:                 265f626b-781c-5eda-aba4-2a22e5a791c0
  Summary:              A Thunderbolt™ 3 docking station
  Plugin:               uefi
  Flags:                updatable|require-ac|registered|needs-reboot
  Vendor:               Dell Inc.
  Version:              0.0.3.18
  Icon:                 computer
  Created:              2018-10-01

Dell TB16 Port Controller 1
  DeviceId:             b3fa3dc04e3450450bb17910417562e5b6cf69d0
  ParentDeviceId:       84edf044a6b53037732cfc7591b65a8d36384cc9
  Guid:                 8fe183da-c94e-4804-b319-0f1ba5457a69
  Guid:                 51182d1b-d279-53e3-a093-ebc625bd9dfd
  Summary:              A Thunderbolt™ 3 docking station
  Plugin:               uefi
  Flags:                updatable|require-ac|registered|needs-reboot
  Vendor:               Dell Inc.
  Version:              0.1.2.17
  Icon:                 computer
  Created:              2018-10-01

Dell TB16 Port Controller 2
  DeviceId:             4bcf1477575b55912993240dd1edd8b0ebb6d491
  ParentDeviceId:       84edf044a6b53037732cfc7591b65a8d36384cc9
  Guid:                 1b52c630-86f6-4aee-9f0c-474dc6be49b6
  Guid:                 de20c70b-4aac-5d1a-bb16-54000590345a
  Summary:              A Thunderbolt™ 3 docking station
  Plugin:               uefi
  Flags:                updatable|require-ac|registered|needs-reboot
  Vendor:               Dell Inc.
  Version:              0.1.2.18
  Icon:                 computer
  Created:              2018-10-01

Dell TB16
  DeviceId:             84edf044a6b53037732cfc7591b65a8d36384cc9
  Guid:                 e7ca1f36-bf73-4574-afe6-a4ccacabf479
  Guid:                 82cee9ac-1917-5f7b-a8ee-d3a469f35666
  Summary:              A Thunderbolt™ 3 docking station
  Plugin:               uefi
  Flags:                updatable|require-ac|registered|needs-reboot
  Vendor:               Dell Inc.
  Version:              0.0.0.0
  Icon:                 computer
  Created:              2018-10-01

THNSN51T02DUK NVMe TOSHIBA 1024GB
  DeviceId:             04e17fcf7d3de91da49a163ffe4907855c3648be
  Guid:                 bfe8d16e-b612-5f26-9526-0123dd679e7d
  Guid:                 a7e9412b-a3cf-5819-9029-105efad314f1
  Guid:                 ad9fe8f7-cdc4-52c9-9fea-31b6f4988ffa
  Serial:               X6IS104ZT1CT
  Summary:              NVM Express Solid State Drive
  Plugin:               nvme
  Flags:                internal|updatable|require-ac|registered|needs-reboot
  Vendor:               Toshiba America Info Systems
  VendorId:             NVME:0x1179
  Version:              5KDA4103
  Icon:                 drive-harddisk
  Created:              2018-10-01
```

```
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000
Boot0000* Gentoo	HD(1,GPT,13a146e5-5ee8-48fc-9928-65e8d873a668,0x800,0x100000)/File(vmlinuz.efi)
```
```
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupdate-124c207d-5db8-4d95-bd31-34fd971b34f9-0
```
```
/boot
├── backup.efi
├── EFI
│   ├── Dell
│   │   └── Bios
│   │       └── Recovery
│   │           ├── BIOS_CUR.RCV
│   │           └── BIOS_PRE.rcv
│   ├── EFI
│   └── gentoo
│       ├── fw
│       ├── fwupdx64.efi
│       └── fwupx64.efi
└── vmlinuz.efi
```
Please answer the following questions:

- Operating system and version: Gentoo (kernel 4.19.0-rc6)
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): using portage/emerge
- Have you tried rebooting? yes
- Are you using an NVMe disk? yes
- Is secure boot enabled (only for the UEFI plugin)? no
```
agamemnon ~ # fwupdmgr get-devices --show-all-devices | grep -C6 "Alternate mode for platform TPM device"

XPS 15 9550 TPM 2.0
  DeviceId:             04d075f2971403e31c1dbdf3b38f709d7c2e749d
  ParentDeviceId:       5ab1e5b4c5e2639722437a5b7c5a8391c75fcabe
  Guid:                 75305a8e-596f-5a3b-9aea-ebee36dc585e
  Guid:                 b2ce3dae-d233-53ce-89e3-4abe40a5b9bf
  Summary:              Alternate mode for platform TPM device
  Plugin:               uefi
  Flags:                internal|require-ac|locked|registered
  Vendor:               Dell Inc.
  Icon:                 computer
  Created:              2018-10-01

agamemnon ~ # fwupdmgr unlock 04d075f2971403e31c1dbdf3b38f709d7c2e749d
Authenticating…        [***************************************]

agamemnon ~ # fwupdmgr get-devices --show-all-devices | grep -C6 "Alternate mode for platform TPM device"

XPS 15 9550 TPM 2.0
  DeviceId:             04d075f2971403e31c1dbdf3b38f709d7c2e749d
  ParentDeviceId:       5ab1e5b4c5e2639722437a5b7c5a8391c75fcabe
  Guid:                 75305a8e-596f-5a3b-9aea-ebee36dc585e
  Guid:                 b2ce3dae-d233-53ce-89e3-4abe40a5b9bf
  Summary:              Alternate mode for platform TPM device
  Plugin:               uefi
  Flags:                internal|require-ac|registered
  Vendor:               Dell Inc.
  Icon:                 computer
  Created:              2018-10-01
  Modified:             2018-10-01

agamemnon ~ # fwupdmgr install https://fwupd.org/downloads/a1a6e10beb96281fa78c62a7d967c8c3a1cf7430-DellTpm2.0_Fw1.3.1.0.cab
Fetching firmware https://fwupd.org/downloads/a1a6e10beb96281fa78c62a7d967c8c3a1cf7430-DellTpm2.0_Fw1.3.1.0.cab
Downloading…           [***************************************] Less than one minute remaining…
Decompressing…         [***************************************]
Device XPS 15 9550 TPM 2.0 [04d075f2971403e31c1dbdf3b38f709d7c2e749d] does not currently allow updates
```
It is in fact unlocked, as evidenced by trying again:
```
agamemnon ~ # fwupdmgr unlock 04d075f2971403e31c1dbdf3b38f709d7c2e749d
Authenticating…        [***************************************]
Device 04d075f2971403e31c1dbdf3b38f709d7c2e749d is not locked
```
Note that restarting the "fwupd" daemon reinstates the "locked" flag, as does rebooting the system.

**Comment by superm1** [comment] 2018-10-01 14:27
(Updated your comment to add back-ticks).

> Note that restarting the "fwupd" daemon reinstates the "locked" flag, as does rebooting the system.

Yes, that's expected behavior.

>   Flags:                internal|require-ac|registered

It looks like after it's unlocked that the updateable flag didn't get put in place on the alternate device.

My guess; you probably need to clear the TPM in BIOS setup before starting.  fwupd won't allow TPM mode switch when the TPM is owned or contains data.

**Comment by superm1** [comment] 2018-10-01 14:31
Hmm, however you have the updateable flag on the 1.2 device.  This might be a bug that was related to the uefi proxy device switchover that happened in 1.1.0.

The flags are "supposed" to be cloned between devices, but since the device is owned by 'uefi' not 'dell' the wrong method probably isn't called anymore.
https://github.com/hughsie/fwupd/blob/master/plugins/dell/fu-plugin-dell.c#L682

**Comment by superm1** [comment] 2018-10-02 19:43
@gentoochainsaw can you please test my branch `wip/superm1/dell-unlock` to see if it helps?  The commit is referenced above.

My current platforms at hand can't switch modes, so I can't check easily myself.

**Comment by superm1** [comment] 2018-10-03 13:47
@gentoochainsaw Do you know if regular BIOS firmware updates are working for you in the current configuration?

That error is peculiar and it makes me wonder if it's related to the way your ESP is arranged.  It doesn't seem like a bug in the TPM update flow now but actually UEFI update flow.

```
/boot
├── backup.efi
├── EFI
│   ├── Dell
│   │   └── Bios
│   │       └── Recovery
│   │           ├── BIOS_CUR.RCV
│   │           └── BIOS_PRE.rcv
│   ├── EFI
│   └── gentoo
│       ├── fw
│       ├── fwupdx64.efi
│       └── fwupx64.efi
└── vmlinuz.efi
```

So a few questions:
1) Where is your ESP actually mounted?  It seems like it's at `/boot`.  It's really odd to me that `vmlinuz.efi` is showing up at the root of `/boot` though`

2) Did you modify `/etc/fwupd/uefi.conf` at all?

3) With that branch in place can you please switch the daemon to verbose and share journal output for `fwupd.service`? (Modify the systemd unit to have `--verbose` in `ExecStart`, reload units, restart `fwupd.service`)

**Comment by gentoochainsaw** [comment] 2018-10-03 13:53
> @gentoochainsaw Do you know if regular BIOS firmware updates are working for you 

Yes, they certainly did. I remember sending the report out for 0.1.8.0 system firmware.

> That error is peculiar and it makes me wonder if it's related to the way your ESP is arranged.

This is my first UEFI installation and it was a bit haphazard, open to improvement suggestions.

> 1. Where is your ESP actually mounted?

```
agamemnon ~ # mount | grep vfat
/dev/nvme0n1p1 on /boot type vfat (rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-15,shortname=mixed,utf8,errors=remount-ro)
```
> It's really odd to me that `vmlinuz.efi` is showing up at the root of `/boot` though

I am using the kernel stub loader and upgrade kernels like this:
```
cd /usr/src/linux && make mrproper && zcat /proc/config.gz > .config && make oldconfig && make menuconfig && make -j8 && cp arch/x86/boot/bzImage /boot/vmlinuz.efi && mount -o remount,rw /sys/firmware/efi/efivars/ && efibootmgr -B -b 0000 && efibootmgr --create --part -1 --disk /dev/nvme0n1 --label Gentoo --loader \vmlinuz.efi && mount -o remount,ro /sys/firmware/efi/efivars
```

> 2. Did you modify `/etc/fwupd/uefi.conf` at all?

Yes.
```
agamemnon ~ # cat /etc/fwupd/uefi.conf 
[uefi]
RequireShimForSecureBoot=true
OverrideESPMountPoint=/boot
```

> 3. With that branch in place

I will be honest with you, I did not use your branch. I applied the patch you attached to this report to fwupd 1.1.2 as a "user patch". It applied cleanly.

**Comment by superm1** [comment] 2018-10-03 14:00
> Yes, they certainly did. I remember sending the report out for 0.1.8.0 system firmware.

OK thanks for confirming.

> This is my first UEFI installation and it was a bit haphazard, open to improvement suggestions.

The part that throws me off is the nested EFI/EFI directories.  If it's working for non TPM updates however though I think it's fine.

> I will be honest with you, I did not use your branch. I applied the patch you attached to this report to fwupd 1.1.2 as a "user patch". It applied cleanly.

Thanks for clarifying.  Let me double check all the other code then to make sure nothing else needs to actually come back with this patch for a backport.  I'd still like to see a verbose daemon log though too.

**Comment by gentoochainsaw** [comment] 2018-10-03 14:13
[fwupd.log](https://github.com/hughsie/fwupd/files/2442356/fwupd.log)

**Comment by superm1** [comment] 2018-10-03 14:54
OK thanks.  I found the problem, it was due to the order of events with Dell plugin running before UEFI plugin.  I've added another patch to that branch that should fix it.

**Comment by gentoochainsaw** [comment] 2018-10-04 07:47
```
agamemnon / # fwupdmgr update
No upgrades for XPS15 9550 Thunderbolt Controller, current is 26.01: 16.00=older
ignoring XPS 15 9550 System Firmware [2da31270d317b076424992de14a0f08ae373c137] as not updatable
ignoring XPS 15 9550 TPM 1.2 [5ab1e5b4c5e2639722437a5b7c5a8391c75fcabe] as not updatable
Downloading 1.3.1.0 for XPS 15 9550 TPM 2.0...
Decompressing…         [***************************************]
Authenticating…        [***************************************]
Updating XPS 15 9550 TPM 2.0 from 0.0.0.0 to 1.3.1.0…          ]
Scheduling…            [***************************************]

An update requires a reboot to complete. Restart now? [Y|n]: Y
```
More soon.

**Comment by gentoochainsaw** [comment] 2018-10-04 08:05
![broken-boot-entry](https://user-images.githubusercontent.com/2817133/46460594-4aeeba00-c7b4-11e8-9f79-acf0a89c4a38.jpg)
So that didn't work fantastically well; I've taken a photo of the boot entry it created. Used the BIOS menu system to try & launch that file manually and I am not convinced it worked.

```
agamemnon ~ # fwupdmgr get-devices --show-all-devices | grep -C6 "Alternate mode for platform TPM device"

XPS 15 9550 TPM 2.0
  DeviceId:             04d075f2971403e31c1dbdf3b38f709d7c2e749d
  ParentDeviceId:       5ab1e5b4c5e2639722437a5b7c5a8391c75fcabe
  Guid:                 75305a8e-596f-5a3b-9aea-ebee36dc585e
  Guid:                 b2ce3dae-d233-53ce-89e3-4abe40a5b9bf
  Summary:              Alternate mode for platform TPM device
  Plugin:               uefi
  Flags:                internal|require-ac|locked|registered
  Vendor:               Dell Inc.
  Icon:                 computer
  Created:              2018-10-04
  UpdateState:          success
```

Does the "success" refer to the staging process only, or does that suggest the update was in fact applied? I ask because the system came back on TPM 1.2 and I saw none of the usual firmware upgrade progress bars on the Dell logo.

**Comment by gentoochainsaw** [comment] 2018-10-04 08:12
Rerunning it, and just checking the boot entries prior to rebooting:
```
agamemnon / # efibootmgr -v
BootNext: 0001
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0000,0001
Boot0000* Gentoo	HD(1,GPT,13a146e5-5ee8-48fc-9928-65e8d873a668,0x800,0x100000)/File(vmlinuz.efi)
Boot0001* Linux Firmware Updater	PciRoot(0x0)/Pci(0x1d,0x0)/Pci(0x0,0x0)/NVMe(0x1,00-08-0D-02-00-13-1D-97)/File(\EFI\gentoo\fwupdx64.efi)
```

**Comment by superm1** [comment] 2018-10-04 11:10
Success does only refer to the staging in this context.

Can you describe more about the behavior when you tried to run the boot entry? No Dell logo whatsoever? Or a message came up?
See the typical white text before Dell logo?

It may be useful to see fwupdate debugging, where you run `/usr/libexec/fwupd/fwupdate --debug` first before staging and then use the same tool to view logs when done.

**Comment by gentoochainsaw** [comment] 2018-10-04 11:13
The system reports no bootable device, in white text, offering F-key prompts for setup etc.
I am able, using the BIOS menus, to create a working boot entry for "vmlinuz.efi" and boot my linux kernel. I am not able to boot/use "fwupdx64.efi" in this way.

**Comment by superm1** [comment] 2018-10-04 11:13
Also can you please try efivar master? That boot entry is suspect to me to a similar problem that was seen on Lenovo (https://github.com/rhboot/efivar/issues/121) specifically with efivar 36 or 35 and NVMe disks.

Upstream hasn't cut a new release yet though.

**Comment by gentoochainsaw** [comment] 2018-10-09 12:11
Waiting for efivar release to be cut.

**Comment by superm1** [comment] 2018-10-09 12:47
Other than testing with master, you should also be able to downgrade to 34 to verify

**Comment by gentoochainsaw** [comment] 2018-10-09 13:52
Thank you, it worked flawlessly with your 2 patches on with efivar 34. Now in TPM 2.0 mode.

**Comment by superm1** [comment] 2018-10-10 17:01
Fixed in master with https://github.com/hughsie/fwupd/commit/dc48bec1576449288b05c882cd4af8ae770486f7

**Closed by superm1** 2018-10-10 17:01 UTC
Labels: bug

**Comment by ignisf** [comment] 2021-03-06 11:56
I am sorry for necrobumping, but I am not able to find the firmware mentioned here (https://fwupd.org/downloads/a1a6e10beb96281fa78c62a7d967c8c3a1cf7430-DellTpm2.0_Fw1.3.1.0.cab) in LVFS' search interface although I was able to use it to change my TPM mode.

Is there some secret stash of firmwares that possibly contains the latest version (which seems to be [1.3.2.8](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=rf87d&oscode=wb64a&productcode=optiplex-3040m-desktop))?
