### ISSUE TITLE
Wrong firmware downloaded for Dell XPS 13 ?

### ISSUE THREAD

**Issue by jamiedbennett** [hughsie/fwupd#339] opened 2017-12-12 16:52 UTC
On a Dell XPS 13 fwupdmgr get-updates shows:

```
XPS 13 9350 TPM 1.2 has firmware updates:
ID:                      com.dell.uefi5034bac4.firmware
GUID:                    d433959e-03ca-524b-92b7-5022eff81a31
Update Version:          5.81.2.1
Update Remote ID:        lvfs
Update Checksum:         SHA1(77ae490f6cf7b03dd6dd485b782bde8274329af7)
Update Location:         https://fwupd.org/downloads/f7375df3c5f903f55ffd64e9ce891da3aa535355-DellTpm1.2_Fw5.81.2.1.cab
XPS 13 9350 System Firmware has firmware updates:
ID:                      com.dell.uefi33773727.firmware
GUID:                    33773727-8ee7-4d81-9fa0-57e8d889e1fa
Update Version:          0.1.5.1
Update Remote ID:        lvfs
Update Checksum:         SHA1(1bb95787c07612137e6cd00ea0bfde61b9a7b7a9)
Update Location:         https://fwupd.org/downloads/8f8215fdf6bb569f98c6ff76b5a48c168b158df8-firmware_XPS_9350_Bios_1.5.1.wu.cab
```
When I try to apply the update through Gnome Software the laptop reboots into the bios flash tool but complains that the firmware is not for this model. It then reboots and boots normally.

To help us pinpoint your issue, please insert the output of the
following commands when ran on the system with the issue:

```shell
$ fwupdmgr --version
client version:	0.9.7
daemon version:	0.9.7
compile-time dependency versions
	appstream-glib:	0.7.1
	gusb:	0.2.11
```

Note, the switch `--version` is only present since version 0.9.6. If you use an
earlier version, please use the package manager to find out the package
version. For example, `dpkg -l fwupd`.

```shell
$ fwupdmgr get-devices
XPS 13 9350 TPM 1.2
  DeviceID:             DELL-d433959e-03ca-524b-92b7-5022eff81a31lu
  Guid:                 d433959e-03ca-524b-92b7-5022eff81a31
  Description:          <p>Updating the system firmware improves performance.</p>
  Plugin:               dell
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              5.81.0.0
  Created:              2017-12-12

XPS 13 9350 TPM 2.0
  DeviceID:             DELL-b62a2412-5ac4-5350-b16e-7e8f4655d096lu
  Guid:                 b62a2412-5ac4-5350-b16e-7e8f4655d096
  Plugin:               dell
  Flags:                internal|require-ac|locked|registered
  Created:              2017-12-12

XPS 13 9350 Thunderbolt Controller
  DeviceID:             c7010000-0092-8518-222c-f4d45c217118
  Guid:                 dbbe0ed9-df91-529c-ac86-8976b78f726d
  Plugin:               thunderbolt
  Flags:                internal|updatable|registered
  DeviceVendor:         Dell
  DeviceVendorId:       TBT:0x00D4
  Version:              15.0
  Created:              2017-12-12

XPS 13 9350 System Firmware
  DeviceID:             UEFI-33773727-8ee7-4d81-9fa0-57e8d889e1fa-dev0
  Guid:                 33773727-8ee7-4d81-9fa0-57e8d889e1fa
  Description:          <p>Updating the system firmware improves performance.</p>
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot
  Version:              0.1.4.18
  VersionLowest:        0.1.4.18
  Created:              2017-12-12

AX88179
  DeviceID:             usb:00:01:02
  Guid:                 da6082b0-a033-5b25-b280-bcba3720eddd
  Guid:                 69b5c44a-b47b-578c-8a91-490fc0715fa1
  Plugin:               usb
  Flags:                registered
  DeviceVendorId:       USB:0x0B95
  Version:              1.0
  Created:              2017-12-12

Quickfire TKL 6keys
  DeviceID:             usb:00:01:01:03:02
  Guid:                 a2d35aa0-2f42-5560-b5ba-8abb588b739b
  Guid:                 752fcb15-1fa3-57a6-ab5a-b37df5f14d45
  Plugin:               usb
  Flags:                registered
  DeviceVendorId:       USB:0x2516
  Version:              1.17
  Created:              2017-12-12

ZELOTES GAME MOUSE
  DeviceID:             usb:00:01:01:01:02
  Guid:                 2198ecf1-548b-50f3-9b53-e3785d904fdb
  Guid:                 efcda824-7a22-5564-a1b0-78d875ed473f
  Plugin:               usb
  Flags:                registered
  DeviceVendorId:       USB:0x1D57
  Version:              1.5
  Created:              2017-12-12

Integrated Webcam HD
  DeviceID:             usb:00:05
  Guid:                 4ec19583-c132-5c27-a9cf-061419e838dc
  Guid:                 6b31e6e6-ba7c-5251-8f4c-7f2571612251
  Plugin:               usb
  Flags:                registered
  DeviceVendorId:       USB:0x0C45
  Version:              86.38
  Created:              2017-12-12

Touchscreen
  DeviceID:             usb:00:04
  Guid:                 57f117e9-edc2-5737-841f-0ee7f3aba8a2
  Guid:                 64ebafc2-62ab-5997-96c6-356a14ff3e67
  Plugin:               usb
  Flags:                registered
  DeviceVendorId:       USB:0x04F3
  Version:              17.17
  Created:              2017-12-12

BCM2045A0
  DeviceID:             usb:00:03
  Guid:                 7a1ba7b9-6bcd-54a4-8a36-d60cc5ee935c
  Guid:                 202e8dd9-1ad3-5346-a380-87272deb7158
  Plugin:               usb
  Flags:                registered
  DeviceVendorId:       USB:0x0A5C
  Version:              1.18
  Created:              2017-12-12

HD Graphics 520
  DeviceID:             ro__sys_devices_pci0000_00_0000_00_02_0
  Guid:                 a3361e1f-f523-5cfc-ad68-e20d0f792003
  Plugin:               udev
  Flags:                internal|registered
  DeviceVendor:         Intel Corporation
  DeviceVendorId:       PCI:0x8086
  Created:              2017-12-12
```

```shell
$ efibootmgr -v
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0001,0002,0003,0004,0006,0005
Boot0000* ubuntu	HD(1,GPT,828120b8-2e4f-43f9-9816-62309bd9935e,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)
Boot0001* Diskette Drive	BBS(Floppy,Diskette Drive,0x0)..BO
Boot0002* Internal HDD	BBS(HD,Internal HDD,0x0)..BO
Boot0003* USB Storage Device	BBS(USB,USB Storage Device,0x0)..BO
Boot0004* CD/DVD/CD-RW Drive	BBS(CDROM,CD/DVD/CD-RW Drive,0x0)..BO
Boot0005* Linux-Firmware-Updater \fwupx64.efi	HD(1,GPT,828120b8-2e4f-43f9-9816-62309bd9935e,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.x.6.4...e.f.i...
Boot0006* UEFI: TOSHIBA THNSNK128GVN8 M.2 2280 128GB, Partition 1	HD(1,GPT,828120b8-2e4f-43f9-9816-62309bd9935e,0x800,0x100000)/File(EFI\boot\bootx64.efi)..BO
```

```shell
$ efivar -l | grep fw
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupdate-33773727-8ee7-4d81-9fa0-57e8d889e1fa-0
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupdate-d433959e-03ca-524b-92b7-5022eff81a31-0
```

```shell
$ tree /boot
/boot
├── abi-4.13.0-17-generic
├── abi-4.13.0-19-generic
├── config-4.13.0-17-generic
├── config-4.13.0-19-generic
├── efi [error opening dir]
├── grub
│   ├── fonts
│   │   └── unicode.pf2
│   ├── grub.cfg
│   ├── grubenv
│   ├── locale
│   │   ├── en_AU.mo
│   │   ├── en_CA.mo
│   │   ├── en_GB.mo
│   │   └── en@quot.mo
│   ├── unicode.pf2
│   └── x86_64-efi
│       ├── acpi.mod
│       ├── adler32.mod
│       ├── affs.mod
│       ├── afs.mod
│       ├── ahci.mod
│       ├── all_video.mod
│       ├── aout.mod
│       ├── appleldr.mod
│       ├── archelp.mod
│       ├── ata.mod
│       ├── at_keyboard.mod
│       ├── backtrace.mod
│       ├── bfs.mod
│       ├── bitmap.mod
│       ├── bitmap_scale.mod
│       ├── blocklist.mod
│       ├── boot.mod
│       ├── bsd.mod
│       ├── bswap_test.mod
│       ├── btrfs.mod
│       ├── bufio.mod
│       ├── cat.mod
│       ├── cbfs.mod
│       ├── cbls.mod
│       ├── cbmemc.mod
│       ├── cbtable.mod
│       ├── cbtime.mod
│       ├── chain.mod
│       ├── cmdline_cat_test.mod
│       ├── cmp.mod
│       ├── cmp_test.mod
│       ├── command.lst
│       ├── configfile.mod
│       ├── core.efi
│       ├── cpio_be.mod
│       ├── cpio.mod
│       ├── cpuid.mod
│       ├── crc64.mod
│       ├── cryptodisk.mod
│       ├── crypto.lst
│       ├── crypto.mod
│       ├── cs5536.mod
│       ├── ctz_test.mod
│       ├── datehook.mod
│       ├── date.mod
│       ├── datetime.mod
│       ├── diskfilter.mod
│       ├── disk.mod
│       ├── div.mod
│       ├── div_test.mod
│       ├── dm_nv.mod
│       ├── echo.mod
│       ├── efifwsetup.mod
│       ├── efi_gop.mod
│       ├── efinet.mod
│       ├── efi_uga.mod
│       ├── ehci.mod
│       ├── elf.mod
│       ├── eval.mod
│       ├── exfat.mod
│       ├── exfctest.mod
│       ├── ext2.mod
│       ├── extcmd.mod
│       ├── fat.mod
│       ├── file.mod
│       ├── fixvideo.mod
│       ├── font.mod
│       ├── fshelp.mod
│       ├── fs.lst
│       ├── functional_test.mod
│       ├── gcry_arcfour.mod
│       ├── gcry_blowfish.mod
│       ├── gcry_camellia.mod
│       ├── gcry_cast5.mod
│       ├── gcry_crc.mod
│       ├── gcry_des.mod
│       ├── gcry_dsa.mod
│       ├── gcry_idea.mod
│       ├── gcry_md4.mod
│       ├── gcry_md5.mod
│       ├── gcry_rfc2268.mod
│       ├── gcry_rijndael.mod
│       ├── gcry_rmd160.mod
│       ├── gcry_rsa.mod
│       ├── gcry_seed.mod
│       ├── gcry_serpent.mod
│       ├── gcry_sha1.mod
│       ├── gcry_sha256.mod
│       ├── gcry_sha512.mod
│       ├── gcry_tiger.mod
│       ├── gcry_twofish.mod
│       ├── gcry_whirlpool.mod
│       ├── geli.mod
│       ├── gettext.mod
│       ├── gfxmenu.mod
│       ├── gfxterm_background.mod
│       ├── gfxterm_menu.mod
│       ├── gfxterm.mod
│       ├── gptsync.mod
│       ├── grub.efi
│       ├── gzio.mod
│       ├── halt.mod
│       ├── hashsum.mod
│       ├── hdparm.mod
│       ├── hello.mod
│       ├── help.mod
│       ├── hexdump.mod
│       ├── hfs.mod
│       ├── hfspluscomp.mod
│       ├── hfsplus.mod
│       ├── http.mod
│       ├── iorw.mod
│       ├── iso9660.mod
│       ├── jfs.mod
│       ├── jpeg.mod
│       ├── keylayouts.mod
│       ├── keystatus.mod
│       ├── ldm.mod
│       ├── legacycfg.mod
│       ├── legacy_password_test.mod
│       ├── linux16.mod
│       ├── linuxefi.mod
│       ├── linux.mod
│       ├── loadbios.mod
│       ├── load.cfg
│       ├── loadenv.mod
│       ├── loopback.mod
│       ├── lsacpi.mod
│       ├── lsefimmap.mod
│       ├── lsefi.mod
│       ├── lsefisystab.mod
│       ├── lsmmap.mod
│       ├── ls.mod
│       ├── lspci.mod
│       ├── lssal.mod
│       ├── luks.mod
│       ├── lvm.mod
│       ├── lzopio.mod
│       ├── macbless.mod
│       ├── macho.mod
│       ├── mdraid09_be.mod
│       ├── mdraid09.mod
│       ├── mdraid1x.mod
│       ├── memdisk.mod
│       ├── memrw.mod
│       ├── minicmd.mod
│       ├── minix2_be.mod
│       ├── minix2.mod
│       ├── minix3_be.mod
│       ├── minix3.mod
│       ├── minix_be.mod
│       ├── minix.mod
│       ├── mmap.mod
│       ├── moddep.lst
│       ├── modinfo.sh
│       ├── morse.mod
│       ├── mpi.mod
│       ├── msdospart.mod
│       ├── mul_test.mod
│       ├── multiboot2.mod
│       ├── multiboot.mod
│       ├── nativedisk.mod
│       ├── net.mod
│       ├── newc.mod
│       ├── nilfs2.mod
│       ├── normal.mod
│       ├── ntfscomp.mod
│       ├── ntfs.mod
│       ├── odc.mod
│       ├── offsetio.mod
│       ├── ohci.mod
│       ├── part_acorn.mod
│       ├── part_amiga.mod
│       ├── part_apple.mod
│       ├── part_bsd.mod
│       ├── part_dfly.mod
│       ├── part_dvh.mod
│       ├── part_gpt.mod
│       ├── partmap.lst
│       ├── part_msdos.mod
│       ├── part_plan.mod
│       ├── part_sun.mod
│       ├── part_sunpc.mod
│       ├── parttool.lst
│       ├── parttool.mod
│       ├── password.mod
│       ├── password_pbkdf2.mod
│       ├── pata.mod
│       ├── pbkdf2.mod
│       ├── pbkdf2_test.mod
│       ├── pcidump.mod
│       ├── play.mod
│       ├── png.mod
│       ├── priority_queue.mod
│       ├── probe.mod
│       ├── procfs.mod
│       ├── progress.mod
│       ├── raid5rec.mod
│       ├── raid6rec.mod
│       ├── random.mod
│       ├── read.mod
│       ├── reboot.mod
│       ├── regexp.mod
│       ├── reiserfs.mod
│       ├── relocator.mod
│       ├── romfs.mod
│       ├── scsi.mod
│       ├── search_fs_file.mod
│       ├── search_fs_uuid.mod
│       ├── search_label.mod
│       ├── search.mod
│       ├── serial.mod
│       ├── setjmp.mod
│       ├── setjmp_test.mod
│       ├── setpci.mod
│       ├── sfs.mod
│       ├── shift_test.mod
│       ├── signature_test.mod
│       ├── sleep.mod
│       ├── sleep_test.mod
│       ├── spkmodem.mod
│       ├── squash4.mod
│       ├── syslinuxcfg.mod
│       ├── tar.mod
│       ├── terminal.lst
│       ├── terminal.mod
│       ├── terminfo.mod
│       ├── test_blockarg.mod
│       ├── testload.mod
│       ├── test.mod
│       ├── testspeed.mod
│       ├── tftp.mod
│       ├── tga.mod
│       ├── time.mod
│       ├── trig.mod
│       ├── tr.mod
│       ├── true.mod
│       ├── udf.mod
│       ├── ufs1_be.mod
│       ├── ufs1.mod
│       ├── ufs2.mod
│       ├── uhci.mod
│       ├── usb_keyboard.mod
│       ├── usb.mod
│       ├── usbms.mod
│       ├── usbserial_common.mod
│       ├── usbserial_ftdi.mod
│       ├── usbserial_pl2303.mod
│       ├── usbserial_usbdebug.mod
│       ├── usbtest.mod
│       ├── verify.mod
│       ├── video_bochs.mod
│       ├── video_cirrus.mod
│       ├── video_colors.mod
│       ├── video_fb.mod
│       ├── videoinfo.mod
│       ├── video.lst
│       ├── video.mod
│       ├── videotest_checksum.mod
│       ├── videotest.mod
│       ├── xfs.mod
│       ├── xnu.mod
│       ├── xnu_uuid.mod
│       ├── xnu_uuid_test.mod
│       ├── xzio.mod
│       ├── zfscrypt.mod
│       ├── zfsinfo.mod
│       └── zfs.mod
├── initrd.img-4.13.0-17-generic
├── initrd.img-4.13.0-19-generic
├── lost+found [error opening dir]
├── memtest86+.bin
├── memtest86+.elf
├── memtest86+_multiboot.bin
├── System.map-4.13.0-17-generic
├── System.map-4.13.0-19-generic
├── vmlinuz-4.13.0-17-generic
├── vmlinuz-4.13.0-17-generic.efi.signed
├── vmlinuz-4.13.0-19-generic
└── vmlinuz-4.13.0-19-generic.efi.signed

```

Please answer the following questions:

- Operating system and version: Ubuntu 17.10
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): apt-get
- Have you tried rebooting? yes
- Are you using an NVMe disk? No
- Is secure boot enabled (only for the UEFI plugin)? No

**Comment by superm1** [comment] 2017-12-12 17:01
Just to be clear, when you're applying updates - are you trying to apply both TPM update and UEFI BIOS update at the same time?  Or just the UEFI BIOS update?  If you were doing both, can you please try to only apply the UEFI BIOS update?  That should help clarify this issue.

**Comment by jamiedbennett** [comment] 2017-12-12 18:21
I applied the System update cleanly on its own. The TPM update complains that the TPM is already owned and to clear the owner, then complains it is the wrong software for this device, then fails to update. 

Previously the TPM update would try to be applied first triggering the failure and subsequent reboot.

**Comment by superm1** [comment] 2017-12-12 18:33
Can you confirm if the TPM really is owned?  You can check in BIOS setup on the TPM page.

**Comment by jamiedbennett** [comment] 2017-12-13 09:12
It looks like it is owned by default on this model as I do not remember doing anything in the bios to claim it.The solution was to clear the TPM in the bios which allowed the firmware to be updated as expected.

The main problems were that the first time I tried this the firmware flashing tool must have tweaked something in the bios (turn UEFI off?) which resulted in an unbootable device. I had to reset the bios to defaults to enable a successful boot. The second more minor problem is that the flashing too is incorrectly reporting that the firmware is not for this model when in fact it is.

**Comment by superm1** [comment] 2017-12-13 12:33
Thanks. Did the machine ship with windows or Linux? When shipped with Windows it will own the tpm by default.

**Comment by superm1** [comment] 2017-12-13 12:34
Regarding causing an unbootable machine, there was a problem with fwupdate in 17.10 that has been fixed very recently, a few days ago.

**Comment by jamiedbennett** [comment] 2017-12-13 13:34
It came with Windows 10 to start with.

**Comment by superm1** [comment] 2017-12-13 13:38
Alright, well that explains why it was owned already.  On Linux it won't be owned until provisioned with the various TPM tools.  I'll confer with some folks to see if we should be blocking in mode upgrades too when owned.  From your behavior described, I think the answer is yes.

**Comment by jamiedbennett** [comment] 2017-12-13 14:04
The other issue was that the TPM update failing blocked the system update
from happening which means that no firmware updates occur until you figure
out how to clear the TPM.

On 13 Dec 2017 1:38 pm, "Mario Limonciello" <notifications@github.com>
wrote:

Alright, well that explains why it was owned already. On Linux it won't be
owned until provisioned with the various TPM tools. I'll confer with some
folks to see if we should be blocking in mode upgrades too when owned. From
your behavior described, I think the answer is yes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hughsie/fwupd/issues/339#issuecomment-351393428>, or mute
the thread

**Comment by superm1** [comment] 2017-12-13 14:10
Good point.  I think that if we block the TPM update when owned that should fix that problem.

Another solution can be to set priority of the update relative to the plugins (eg if you call `fwupdmgr update` run **UEFI** update before **DELL** updates) and don't allow both **UEFI** and **DELL** to both stage updates for the same reboot. @hughsie what do you think of this?

**Comment by hughsie** [comment] 2017-12-13 14:12
I think blocking the TPM update when owned is probably the most pragmatic.

**Comment by superm1** [comment] 2017-12-13 16:14
I confirmed that we should have been blocking owned upgrades too.  I've filed a PR for this.

**Comment by superm1** [comment] 2017-12-13 18:28
@jamiedbennett thanks for your help in reporting and providing the details that root caused this.  I've committed to master and 0.9.x branches and it will be in the next fwupd releases.

**Closed by superm1** 2017-12-13 18:28 UTC

**Comment by jamiedbennett** [comment] 2017-12-13 20:50
@superm1 Thank you.

**Comment by 8none1** [comment] 2017-12-14 13:53
@superm1 could the next release be SRU'd in to Xenial as well?

**Comment by superm1** [comment] 2017-12-14 14:03
@8none1 This particular issue won't affect xenial.  It's only an issue when the version of fwupd supports both Dell TPM and UEFI capsule updates.
Dell TPM updates weren't introduced until after the version in xenial.  I'd love to backport the latest release of fwupd into xenial but it's blocked by a mess of other dependencies that need to be backported.  See https://github.com/hughsie/fwupd/issues/301#issuecomment-342153899 for more details on the stuff that needs to come back.  Some of the things that need to come back aren't really SRU candidates either (like glib2).
